# Generated by Django 2.2.5 on 2019-11-07 14:44

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191105_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_shop_image_path),
        ),
    ]
